package com.liferay.timesheet.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.liferay.timesheet.model.TaskSession;
import com.liferay.timesheet.service.TaskSessionLocalServiceUtil;

/**
 * The extended model base implementation for the TaskSession service. Represents a row in the &quot;timesheet_TaskSession&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TaskSessionImpl}.
 * </p>
 *
 * @author Istvan Sajtos
 * @see TaskSessionImpl
 * @see com.liferay.timesheet.model.TaskSession
 * @generated
 */
public abstract class TaskSessionBaseImpl extends TaskSessionModelImpl
    implements TaskSession {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a task session model instance should use the {@link TaskSession} interface instead.
     */
    public void persist() throws SystemException {
        if (this.isNew()) {
            TaskSessionLocalServiceUtil.addTaskSession(this);
        } else {
            TaskSessionLocalServiceUtil.updateTaskSession(this);
        }
    }
}
